name: Automatically merge json file

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  autocommit_if_modified:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          # token: ${{ secrets.AUTOCOMMIT_GITHUB_TOKEN }}
      
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35.7.8
        with:
          files: |
            **/*DUMMY*.json
      
      - name: Print changed files
        run: echo ${{ steps.changed_files.outputs.all_changed_files }}
      
      - name: combine all json to one file with all uniq strings as json
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          FILES=(`find . -name "*DUMMY*.json"`)
          DATA=$(jq -s 'flatten|sort|unique' "${FILES[@]}")
          echo "$DATA" > allUsers.json
          cat allUsers.json
          ls -l .
      
      - name: Commit changes
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          message: "AutoUpdate allUsers"
          add: "allUsers.json"

